### ISSUE TITLE
sd_update填充分区异常

### ISSUE THREAD

**Issue by Suphappy** [friendlyarm/sd-fuse_h3#7]
打包后的user分区有大量保留扇区
<img width="710" alt="企业微信截图_17205065885167" src="https://github.com/friendlyarm/sd-fuse_h3/assets/58248259/4da78929-8890-4263-93cb-f0bbfaa1a7f8">

**Comment by Suphappy** [comment]
在fusing.sh最后加上就可以了，应该是漏掉了
resize2fs -f /dev/${DEV_PART}

**Comment by friendlyarm** [comment]
把卡插到板子上第一次运行时，在 ramdisk 阶段会自动扩展该分区的

**Comment by Suphappy** [comment]
> 把卡插到板子上第一次运行时，在 ramdisk 阶段会自动扩展该分区的

请问是在哪个脚本执行的呢？还有个问题需要请教一下，我现在先加一个分区用来存放特殊数据，但是我不想在制作img的时候填充(会导致img很大)，我想是在启动时才去创建这个分区并且格式化。请问需要在哪里实现呢？sd_update是执行程序，我看不到具体的操作
